CREATE TABLE EXAMPLE_ENTITY
(
    ID          varchar      NOT NULL PRIMARY KEY,
    NAME        varchar(255) NOT NULL,
    DESCRIPTION varchar(255),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT  TIMESTAMP
);